import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';
import Image from 'next/image';
import { BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';
import Title from '../components/Title';

export default function Home() {
  
  const [cityName, setCityName] = useState('');
  const [weather, setWeather] = useState({});
  const [isLoading, setisLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${cityName.toLowerCase()}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchData = (e) => {
    e.preventDefault();
    setisLoading(true);
    axios.get(url).then((response) => {
        setWeather(response.data);
        console.log(response.data); 
    }).catch((error) => {
      console.log(error);
    });
    setCityName('');
    setisLoading(false);
  }

  if (isLoading){
    return <Spinner />
  } else {
    return (
      <div className='font-sora'>
        <Head >
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
       <Title />
       <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />

       <Image
            src="https://images.unsplash.com/photo-1552845108-5f775a2ccb9b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
            alt="Wallpaper"
            fill='fill'
            className='object-cover'
       />
          
        <div className='relative flex justify-between items-center max-w-[500px] pt-4 text-white w-full m-auto z-[10]'>
            <form className='flex justify-between items-center w-full mt-10 p-3 bg-transparent border border-gray-300 rounded-2xl '>
              <div>
                <input
                  onChange={(e) => setCityName(e.target.value)}
                  className='bg-transparent border-none text-white focus:outline-none'
                  type="text"
                  placeholder='Search City' />
              </div>
              <button className='cursor-pointer bg-transparent' onClick={fetchData} ><BsSearch size={20} /></button>
            </form>
            </div>
           {weather.main && <Weather data={weather} /> }  
  
      </div>
    )
  }
}
